name: release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: please
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          config-file: .github/configs/release-please.config.json
          manifest-file: .github/configs/release-please.manifest.json
