
name: release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: publish
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build Plugin
        run: yarn build

      - name: Pack Plugin
        run: yarn plugin:pack

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: dev.sese.flexbar_home_assistant.flexplugin
